swagger: '2.0'
info:
  title: Medical Symptoms API
  version: '1.0.0'
paths:
  /symptoms:
    post:
      summary: Submit medical symptoms
      description: Endpoint to submit a patient's medical symptoms.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: symptoms
          description: Patient symptoms data
          required: true
          schema:
            type: object
            properties:
              Age:
                type: integer
              Gender:
                type: string
                enum: ['Male', 'Female', 'Other']
              itching:
                type: boolean
              skin_rash:
                type: boolean
              joint_pain:
                type: boolean
              stomach_pain:
                type: boolean
              acidity:
                type: boolean
              vomiting:
                type: boolean
              fatigue:
                type: boolean
              weight_gain:
                type: boolean
              anxiety:
                type: boolean
              cough:
                type: boolean
              high_fever:
                type: boolean
              sweating:
                type: boolean
              dehydration:
                type: boolean
              headache:
                type: boolean
              yellowish_skin:
                type: boolean
              nausea:
                type: boolean
              loss_of_appetite:
                type: boolean
              constipation:
                type: boolean
              mild_fever:
                type: boolean
              yellowing_of_eyes:
                type: boolean
              acute_liver_failure:
                type: boolean
              fluid_overload:
                type: boolean
              malaise:
                type: boolean
              phlegm:
                type: boolean
              chest_pain:
                type: boolean
              weakness_in_limbs:
                type: boolean
              fast_heart_rate:
                type: boolean
              muscle_weakness:
                type: boolean
              dizziness:
                type: boolean
              cramps:
                type: boolean
              swelling_of_stomach:
                type: boolean
              irregular_sugar_level:
                type: boolean
      responses:
        200:
          description: Successful prediction response
          content:
            application/json:
              schema:
                type: object
                properties:
                  prediction:
                    type: string
                    description: Predicted value based on symptoms          
        400:
          description: Invalid input, missing required fields
        500:
          description: Internal server error